const examDate = new Date('2026-08-29T00:00:00+08:00');
const studyWindow = 40;
const today = new Date('2026-07-14T00:00:00+08:00');
const scheduleTemplates = [
  ['审计','审计概述','建立审计语言：三方关系人、认定、保证程度、审计风险',1],['税法','税法总论','掌握税法要素、税收立法与税种体系',1],['审计','审计计划','理解初步业务活动、重要性与错报',1],['税法','增值税法','判断征税范围与税率，建立销项税框架',1],['税法','增值税法','进项税确认、不得抵扣项目与应纳税额计算',1.5],['审计','审计证据','证据可靠性、审计程序、函证',1],['审计','风险评估','从财报层次到认定层次识别重大错报风险',1],['税法','增值税法','增值税综合题：销售额、视同销售、特殊业务',1.5],['税法','消费税法','税目、征税环节与组成计税价格',1],['审计','风险应对','控制测试、实质性程序与风险的匹配',1],['税法','消费税法','消费税应纳税额计算与真题模型',1.5],['审计','销售与收款循环','收入发生、截止、完整性与函证程序',1],['税法','企业所得税法','收入确认与不征税/免税收入',1.5],['税法','企业所得税法','扣除项目、不得扣除项目与纳税调整',1.5],['审计','生产与存货循环','存货监盘、计价与截止测试',1],['税法','企业所得税法','优惠政策与应纳税所得额综合计算',1.5],['审计','货币资金','银行存款函证、未达账项与舞弊风险',1],['税法','个人所得税法','所得类型与居民/非居民纳税义务',1],['税法','个人所得税法','综合所得、专项附加扣除与专项扣除',1.5],['审计','舞弊与法律法规','管理层凌驾控制、舞弊风险与审计责任',1],['审计','审计沟通','与治理层沟通事项与前后任沟通',1],['税法','个人所得税法','分类所得、股权激励与财产转让计算',1.5],['税法','土地增值税','扣除项目、增值额与四级超率累进税率',1.5],['审计','特殊项目','会计估计、关联方、持续经营',1],['税法','房产税/契税','纳税人、计税依据与税收优惠',1],['税法','小税种','车辆购置税、车船税、印花税',1.5],['审计','完成审计工作','期后事项、书面声明与错报汇总',1],['审计','审计报告','意见类型、关键审计事项与非无保留意见',1.5],['税法','国际税收','常设机构、受益所有人与境外所得抵免',1],['税法','资源税/环保税','计税依据、优惠与计算题',1],['审计','独立性','经济利益、商业关系与防范措施',1.5],['税法','小税种与征管','城建税、土地使用税、征收管理与行政法制',1],['审计','高频母题','审计100道母题：概念与判断题第一轮',1],['税法','高频母题','税法100道母题：大税种计算第一轮',1.5],['审计','真题演练','审计主观题答题框架与关键词训练',1],['税法','真题演练','税法综合计算题限时训练',1.5],['审计','背诵冲刺','背诵宝典与必备清单：审计高频考点',1],['税法','背诵冲刺','税率表与背诵宝典：易混规定',1],['综合','错题二刷','复盘错题原因，完成一套混合小测',1.5],['综合','考前冲刺','只看错题、口诀、必备清单，保持答题手感',2]
];
const knowledge = [
  {subject:'审计',title:'审计主线：风险如何变成证据？',text:'管理层认定 → 重大错报风险 → 审计程序 → 审计证据 → 审计意见。做题时先找风险，再找对应程序。',tag:'流程图 · 核心骨架'},
  {subject:'审计',title:'函证：发出、控制、回函、替代',text:'注册会计师保持控制是核心。积极式函证未回函时考虑再次发函，并在必要时实施替代程序。',tag:'高频 · 4次/5年'},
  {subject:'审计',title:'审计报告意见判断',text:'先判断错报是否重大，再判断是否广泛；再区分审计范围是否受限，落到保留、否定或无法表示意见。',tag:'主观题 · 关键词'},
  {subject:'税法',title:'增值税计算四步法',text:'先判断征税范围与税率，再确定销售额，计算销项税，最后处理进项税与不得抵扣项目。',tag:'计算 · 第一优先级'},
  {subject:'税法',title:'企业所得税：会计利润到应纳税所得额',text:'收入确认 → 扣除项目 → 纳税调增调减 → 优惠 → 应纳税额。把每个事项放回这条流水线。',tag:'计算 · 第一优先级'},
  {subject:'税法',title:'土地增值税四层税率',text:'增值额 ÷ 扣除项目金额得到增值率，再按四级超率累进税率计算。扣除项目是最容易失分的入口。',tag:'计算 · 易错'}
];
const questions = [
  {id:1,subject:'审计',type:'判断框架',title:'某项审计证据来自被审计单位内部，但内部控制有效，可靠性如何判断？',answer:'可靠性通常受来源和性质影响。内部来源在内控有效时可靠性会增强，但仍需结合直接获取、文件记录等因素综合判断。',reason:'不要把“内部来源”机械理解为不可靠。'},
  {id:2,subject:'审计',type:'报告判断',title:'财务报表存在重大错报但不具有广泛性，应出具哪类意见？',answer:'通常考虑保留意见；若错报重大且具有广泛性，则进一步考虑否定意见。',reason:'判断顺序：重大性 → 广泛性 → 意见类型。'},
  {id:3,subject:'税法',type:'计算题',title:'增值税综合题的第一步是什么？',answer:'先判断各项业务是否属于征税范围，再确定适用税率或征收率，最后进入销售额、销项税和进项税计算。',reason:'错题常见原因：直接套税率，没有先识别业务性质。'},
  {id:4,subject:'税法',type:'计算题',title:'企业所得税综合题为什么要先看会计利润？',answer:'企业所得税通常以会计利润为起点，通过收入、扣除、纳税调整和税收优惠计算应纳税所得额。',reason:'错题常见原因：把会计口径和税法口径混为一谈。'},
  {id:5,subject:'税法',type:'易混辨析',title:'零税率与免税是否相同？',answer:'不相同。零税率仍属于应税项目，整体税率为零；免税则是税法给予的免除征税待遇，进项税处理也可能不同。',reason:'这是税法高频概念辨析点。'}
];
const chapterQuestions = chapterLibrary.map((k,i)=>({id:1000+i,subject:k.s,type:'章节自测',chapter:k.c,title:`学完“${k.c}”后，请先说出它的解题主线，再说出一个最容易漏掉的条件。`,answer:`主线：${k.flow}。关键条件：${k.points[0]}`,reason:`本章复盘重点：${k.points.slice(0,2).join('；')}`}));
function classifyImported(text,subject){const rules=subject==='审计'?[['独立性','独立性'],['职业道德','职业道德基本原则'],['函证|审计证据|分析程序','审计证据'],['抽样|货币单元','审计抽样方法'],['计划|重要性|错报','审计计划'],['风险评估|重大错报风险|了解被审计单位','风险评估'],['控制测试|实质性程序|风险应对','风险应对'],['销售|收款|收入','销售与收款循环'],['存货|生产|监盘','生产与存货循环'],['货币资金|银行存款','货币资金'],['舞弊|法律法规','对舞弊和法律法规的考虑'],['治理层|前任|后任|沟通','审计沟通'],['专家|内部审计|集团','利用他人的工作'],['会计估计|关联方|持续经营|期后|书面声明','其他特殊项目'],['审计报告|意见类型|关键审计事项','审计报告'],['内部控制|质量管理|项目质量复核','企业内部控制审计']]:[['增值税|进项税|销项税|留抵','增值税法'],['消费税|卷烟|白酒|小汽车','消费税法'],['企业所得税|纳税调整|扣除项目|应纳税所得额','企业所得税法'],['个人所得税|工资|综合所得|专项附加','个人所得税法'],['关税|船舶吨税','关税法和船舶吨税法'],['资源税|环境保护税|污染物','资源税法和环境保护税法'],['土地增值税|契税|房产税','房产税法、契税法和土地增值税法'],['车船税|车辆购置税|印花税','车辆购置税法、车船税法和印花税法'],['国际税收|常设机构|受益所有人|转让定价','国际税收税务管理实务'],['征收管理|纳税申报|税务机关|行政复议','税收征收管理法'],['城镇土地使用税|耕地占用税','城镇土地使用税法和耕地占用税法']];for(const [re,c] of rules)if(new RegExp(re).test(text))return c;return subject==='审计'?'审计概述':'税法总论';}
function importedQuestion(q){const chapter=classifyImported(q.text,q.subject);const k=chapterLibrary.find(x=>x.c===chapter)||chapterLibrary.find(x=>x.s===q.subject)||chapterLibrary[0];return {...q,type:'资料母题',chapter,title:q.text,answer:`学习版答案与解析：本题应先按“${k.flow}”拆解。核心判断依据：${k.points.slice(0,2).join('；')}。原资料未提供标准答案，本解析按当前学习资料整理，建议二刷时结合题干条件逐项核对。`,reason:`易错点：${k.points[2]||k.points[0]}`,imported:true};}
const questionBank = [...questions,...chapterQuestions,...importedQuestions.map(importedQuestion)];
// 修改 state 初始化代码：
const state = JSON.parse(localStorage.getItem('cpa40-state') || '{"completed":[],"wrong":[],"studyMinutes":0,"streak":0,"lastDate":""}');
const todayStr = new Date().toLocaleDateString();
if (state.lastDate !== todayStr) {
    state.studyMinutes = 0; // 新的一天，重置今日时长
    state.lastDate = todayStr; // 更新日期记录
    save(); // 保存状态
}
const app = document.querySelector('#app');
let currentView = 'home';
const daysUntil = date => Math.max(0, Math.ceil((date - today) / 86400000));
const dateForDay = day => { const d = new Date(today); d.setDate(d.getDate() + day - 1); return d.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric',weekday:'short'}); };
const save = () => {
    state.lastDate = new Date().toLocaleDateString(); // 确保每次保存都带上日期
    localStorage.setItem('cpa40-state', JSON.stringify(state));
};
const subjectCount = subject => scheduleTemplates.filter(x => x[0] === subject).length;
const completedCount = subject => scheduleTemplates.filter((x,i) => (!subject || x[0] === subject) && state.completed.includes(i)).length;
const pct = subject => Math.round(completedCount(subject) / subjectCount(subject) * 100);
const tag = subject => `<span class="tag ${subject==='审计'?'audit':subject==='税法'?'tax':''}">${subject}</span>`;
const pendingIndexes = () => scheduleTemplates.map((_,i)=>i).filter(i=>!state.completed.includes(i));
const adaptiveMeta = index => { const pending=pendingIndexes(); const rank=pending.indexOf(index); if(rank<0)return {label:'已完成',date:'已完成',adjusted:index+1}; return {label:rank===0?'今日':`顺延第${rank+1}项`,date:dateForDay(rank+1),adjusted:rank+1}; };
function sourceNote(){return `<p class="source-note">考试日期与范围依据：中国注册会计师协会2026年考试时间公告及2026年专业阶段考试大纲。专业阶段考试为2026年8月29日-30日；税法相关法规截止2025年12月31日，增值税相关法规截止2026年1月31日。<br><a href="https://www.cicpa.org.cn/xxfb/tzgg/202512/t20251210_65740.html" target="_blank" rel="noreferrer">考试时间来源 ↗</a>　<a href="https://www.cicpa.org.cn/xxfb/tzgg/202603/t20260304_65840.html" target="_blank" rel="noreferrer">考试大纲来源 ↗</a></p>`;}
function taskCard(index){const t=scheduleTemplates[index];const done=state.completed.includes(index);const meta=adaptiveMeta(index);return `<article class="task-card" data-study="${index}"><div class="task-index">${done?'✓':'D'+(index+1)}</div><div class="task-main"><h3>${t[1]}</h3><div class="task-meta">${tag(t[0])}<span>${t[2]}</span><span>${t[3]}h</span><span class="tag ${done?'done-tag':''}">${meta.label} · ${meta.date}</span></div></div><button class="check-button ${done?'done':''}" data-complete="${index}">${done?'✓':'○'}</button></article>`;}
function renderHome(){const upcoming=pendingIndexes();const next=upcoming[0]??39;const done=state.completed.length;const second=upcoming[1]??next;app.innerHTML=`<section class="view"><section class="hero"><p class="eyebrow">${upcoming.length?adaptiveMeta(next).label:'40天计划已完成'} · 60分通过导向</p><h2>把有限时间，花在最值分的地方。</h2><p class="hero-copy">系统会根据完成情况自动把未完成任务向后顺延，把提前完成释放出来的时间交给下一项。</p><div class="countdown-row"><span class="countdown-number">${daysUntil(examDate)}</span><span class="countdown-label">天<br>距2026专业阶段考试</span></div><span class="window-pill">✦ 重点学习窗口：${studyWindow} 天</span></section><div class="section-head"><h2>成绩仪表</h2><span class="tag">${done}/40 日完成</span></div><section class="stats-grid"><div class="stat-card"><span class="stat-label">总任务完成</span><strong class="stat-value">${Math.round(done/40*100)}%</strong></div><div class="stat-card"><span class="stat-label">连续学习</span><strong class="stat-value">${state.streak||0} 天</strong></div><div class="stat-card"><span class="stat-label">今日学习</span><strong class="stat-value">${state.studyMinutes||0}m</strong></div><div class="stat-card"><span class="stat-label">需复习</span><strong class="stat-value">${Math.max(1,Math.round(done*.35))} 个</strong></div></section><div class="section-head"><h2>两科进度</h2><button data-view-jump="plan">看完整计划 →</button></div><section class="panel dual-progress"><div class="progress-line"><span>审计</span><div class="progress-bar"><div class="progress-fill" style="width:${pct('审计')}%;background:#7caac3"></div></div><strong>${pct('审计')}%</strong></div><div class="progress-line"><span>税法</span><div class="progress-bar"><div class="progress-fill" style="width:${pct('税法')}%;background:#e66b4f"></div></div><strong>${pct('税法')}%</strong></div><div class="insight">智能重排规则：未完成任务自动顺延；提前完成的任务保持完成状态，后续未完成任务立即前移。</div></section><div class="section-head"><h2>今日任务</h2><span class="tag">${upcoming.length?adaptiveMeta(next).date:'已完成'}</span></div>${taskCard(next)}${upcoming.length>1?taskCard(second):''}<div class="section-head"><h2>今天复习</h2><button data-view-jump="review">进入复习 →</button></div><section class="review-card"><div class="review-date"><span>3天后复习队列</span><span>自动生成</span></div><h3>把刚才的错题，用一句话讲给自己听</h3><p class="task-meta">完成学习任务后，系统会把知识点加入3天复习队列。</p></section>${sourceNote()}</section>`;}
function dayCard(t,i){const done=state.completed.includes(i);const meta=adaptiveMeta(i);return `<article class="day-card ${done?'done':''}" data-study="${i}"><div><div class="day-number">${String(i+1).padStart(2,'0')}</div><div class="day-date">${done?'已完成':meta.date}</div></div><div><div class="day-title">${tag(t[0])} ${t[1]}</div><div class="day-goal">${t[2]}</div><div class="day-open">${done?'已完成 · 可再次学习':meta.label+' · 点击进入知识库 + 题库'}</div></div><div class="time">${t[3]}h<br><button class="check-button ${done?'done':''}" data-complete="${i}">${done?'✓':'○'}</button></div></article>`;}
function renderPlan(){app.innerHTML=`<section class="view"><div class="section-head"><div><p class="eyebrow">YOUR 40-DAY SPRINT</p><h2>学习计划</h2></div><span class="tag">${state.completed.length}/40 完成</span></div><div class="adaptive-note"><strong>智能重排已开启</strong><br>计划不会因为漏学而失效：下一项未完成任务自动成为“今日”，后续任务按剩余顺序顺延；提前完成则自动前移。</div><div class="plan-toolbar"><button class="filter-chip active" data-plan-filter="全部">全部</button><button class="filter-chip" data-plan-filter="审计">审计</button><button class="filter-chip" data-plan-filter="税法">税法</button><button class="filter-chip" data-plan-filter="未完成">未完成</button></div><div class="day-list" id="dayList">${scheduleTemplates.map((t,i)=>dayCard(t,i)).join('')}</div>${sourceNote()}</section>`;document.querySelectorAll('[data-plan-filter]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-plan-filter]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.planFilter;document.querySelector('#dayList').innerHTML=scheduleTemplates.map((t,i)=>[t,i]).filter(([t,i])=>f==='全部'||(f==='未完成'&&!state.completed.includes(i))||t[0]===f).map(([t,i])=>dayCard(t,i)).join('');bindComplete();bindStudy();});}
function knowledgeCard(k){return `<article class="knowledge-card ${k.subject==='审计'?'audit':''}"><p class="eyebrow">${k.subject} · ${k.tag}</p><h3>${k.title}</h3><p>${k.text}</p><div class="knowledge-foot"><span class="tag">理解卡</span><button class="secondary-button" data-explain="quick" data-title="${k.title}" data-text="${k.text}">查看解析</button></div></article>`;}
function chapterCard(k){return `<article class="knowledge-card ${k.s==='审计'?'audit':''}" data-study-chapter="${k.c}"><div class="question-head"><p class="eyebrow">${k.s} · ${k.p}</p><span class="tag">${k.t}</span></div><h3>${k.c}</h3><p>${k.summary}</p><div class="knowledge-foot"><span class="tag">${k.points.length} 个重点</span><button class="secondary-button" data-chapter-detail="${k.c}">打开学习页</button></div></article>`;}
function renderLibrary(){const audit=chapterLibrary.filter(k=>k.s==='审计');const tax=chapterLibrary.filter(k=>k.s==='税法');app.innerHTML=`<section class="view"><div class="section-head"><div><p class="eyebrow">KNOWLEDGE NAVIGATOR</p><h2>知识库</h2></div><span class="tag">${chapterLibrary.length} 个章节卡</span></div><div class="filter-row"><button class="filter-chip active" data-lib-filter="全部">全部</button><button class="filter-chip" data-lib-filter="审计">审计 ${audit.length}</button><button class="filter-chip" data-lib-filter="税法">税法 ${tax.length}</button></div><div class="knowledge-grid" id="knowledgeGrid">${chapterLibrary.map(chapterCard).join('')}</div><div class="section-head"><h2>速记卡</h2><span class="tag">魔法口诀 / 三色笔记</span></div><div class="knowledge-grid">${knowledge.map(knowledgeCard).join('')}</div><div class="section-head"><h2>资料索引</h2><span class="tag">本地资料已接入</span></div><div class="outline"><details open><summary>已纳入学习内容的资料</summary><p>${materialSources.map(x=>`<br>• ${x[0]}：${x[1]}`).join('')}</p></details><details><summary>2026官方考试大纲补充</summary><p>官方大纲强调：税法涉及法规截至2025年12月31日，增值税相关法规截至2026年1月31日；网页已将“税种判断—计税—申报/征管—风险判断”纳入税法学习路径。</p></details></div><p class="insight">点击任意章节卡会进入完整学习页：先读知识点，再做对应题目，最后标记完成。</p>${sourceNote()}</section>`;document.querySelectorAll('[data-lib-filter]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-lib-filter]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.libFilter;document.querySelector('#knowledgeGrid').innerHTML=chapterLibrary.filter(k=>f==='全部'||k.s===f).map(chapterCard).join('');bindStudy();});document.querySelectorAll('[data-chapter-detail]').forEach(btn=>btn.onclick=()=>openChapter(btn.dataset.chapterDetail));}
function questionCard(q){const wrong=state.wrong.includes(q.id);return `<article class="question-card"><div class="question-head"><span class="question-type">${q.subject} · ${q.type}${q.chapter?' · '+q.chapter:''}</span>${wrong?'<span class="tag tax">待复盘</span>':''}</div><p>${q.title}</p>${q.source?`<div class="question-source">来源：${q.source}</div>`:''}<div class="question-actions"><button class="secondary-button" data-explain="answer" data-title="${q.title}" data-answer="${q.answer}" data-reason="${q.reason}">看解析</button><button class="secondary-button" data-wrong="${q.id}">${wrong?'已加入错题':'加入错题'}</button><button class="secondary-button" data-explain="reason" data-title="${q.title}" data-reason="${q.reason}">错因提示</button></div></article>`;}
function chapterForTask(t){return chapterLibrary.find(k=>k.c===t[1])||chapterLibrary.find(k=>k.s===t[0]&&k.p.startsWith('A'))||chapterLibrary[0];}
function chapterDeepDive(k){const isAudit=k.s==='审计';const isTax=!isAudit;const example=k.c.includes('增值税')?'某企业同时销售货物、提供服务并取得价外费用，必须先逐项归类，再分别匹配税率、销售额和进项税处理。':k.c.includes('企业所得税')?'某企业账面利润已经形成，但税法要继续判断收入是否免税、费用是否限额扣除、资产折旧和优惠是否需要调整。':k.c.includes('个人所得税')?'同一纳税人取得工资、劳务、股权激励或财产转让收入时，不能直接套一个税率，必须先确认所得类型。':k.c.includes('审计报告')?'案例给出重大错报、审计范围受限或强调事项时，先标记事实，再判断重大性、广泛性和意见影响。':isAudit?'案例题中先圈出被审计单位的业务、账户和认定，再把风险翻译成可执行的审计程序。':'案例题中先圈出纳税人、征税对象、计税依据和税收优惠，再进入公式。';const explain=isAudit?`这一章的核心不是背结论，而是把审计人员的判断过程复述出来：${k.flow}。遇到新案例时，先问“可能错在哪里”，再问“什么证据能证明或排除它”。`:`这一章的核心是把政策规则变成稳定的计算顺序：${k.flow}。先分类、后取数、再套规则，最后检查优惠、扣除和纳税期限。`;const pitfalls=isAudit?['把审计目标、管理层认定和审计程序混为一谈','只写“应当检查”，不写检查对象、目的和应对的风险','看到一个结论就停止判断，没有继续检查重大性、广泛性或证据可靠性']:['看到税率就直接计算，没有先判断征税范围和业务性质','忽略计税依据中的价外费用、扣除限额、不得抵扣和优惠条件','计算结束后不复核纳税义务发生时间、申报口径和单位'];return {explain,example,pitfalls};}
function openChapter(name){const k=chapterLibrary.find(x=>x.c===name)||chapterLibrary[0];const qs=questionBank.filter(q=>q.subject===k.s).filter(q=>q.type==='章节自测'&&q.title.includes(k.c)).concat(questionBank.filter(q=>q.subject===k.s&&q.type!=='章节自测')).slice(0,3);const deep=chapterDeepDive(k);openModal(`${k.s} · ${k.c}`,'KNOWLEDGE → PRACTICE',`<p>${k.summary}</p><div class="deep-section"><strong>这一章到底在解决什么问题？</strong><p>${deep.explain}</p></div><div class="study-flow"><strong>解题流程</strong><br>${k.flow}</div><h3>必须掌握</h3><ul>${k.points.map(x=>`<li>${x}</li>`).join('')}</ul><div class="deep-section"><strong>典型场景</strong><p>${deep.example}</p></div><div class="deep-section"><strong>易错提醒</strong><ul>${deep.pitfalls.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="study-source">资料依据：${k.s==='审计'?'审计基础讲义、三色笔记、背诵宝典、魔法口诀、必备清单':'税法小白入门、三色笔记、背诵宝典、魔法口诀、税率表、必备清单'}</div><h3>现在练一题</h3>${qs.map(q=>`<div class="study-question"><b>${q.title}</b><br><button class="secondary-button" data-explain="answer" data-title="${q.title}" data-answer="${q.answer}" data-reason="${q.reason}">看解析</button><button class="secondary-button" data-wrong="${q.id}">加入错题</button></div>`).join('')}<div class="study-actions"><button class="primary-button" data-go-view="questions">进入题库</button><button class="secondary-button" data-go-view="library">返回知识库</button></div>`);bindPrepared();bindComplete();}
function openStudy(index){const t=scheduleTemplates[index];const k=chapterForTask(t);const deep=chapterDeepDive(k);openModal(`Day ${index+1} · ${t[1]}`,'TODAY TASK → LEARN',`<div class="study-kicker">${tag(t[0])} <span class="tag">建议 ${t[3]} 小时</span><span class="tag">${adaptiveMeta(index).label}</span></div><h3>${t[2]}</h3><p>${k.summary}</p><div class="deep-section"><strong>先理解</strong><p>${deep.explain}</p></div><div class="study-flow"><strong>本次学习闭环</strong><br>① 理解：${k.flow}<br>② 回忆：用自己的话复述1遍<br>③ 训练：完成下方对应题目<br>④ 复习：3天后再次回忆</div><h3>本次必学</h3><ul>${k.points.slice(0,4).map(x=>`<li>${x}</li>`).join('')}</ul><div class="deep-section"><strong>今天特别注意</strong><p>${deep.example}</p></div><div class="study-actions"><button class="primary-button" data-open-chapter="${k.c}">打开完整知识卡</button><button class="secondary-button" data-go-view="questions">进入题库训练</button><button class="secondary-button" data-complete="${index}">学习完成，打卡</button></div>`);bindPrepared();bindComplete();}
function bindStudy(){document.querySelectorAll('[data-study]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-complete]'))return;openStudy(Number(el.dataset.study));});document.querySelectorAll('[data-chapter-detail]').forEach(btn=>btn.onclick=()=>openChapter(btn.dataset.chapterDetail));}
function renderQuestions(){app.innerHTML=`<section class="view"><div class="section-head"><div><p class="eyebrow">QUESTION LAB</p><h2>题库 & 错题</h2></div><button class="primary-button" data-prebuilt="quiz">今日重点小测</button></div><div class="panel"><div class="progress-line"><span>错题掌握</span><div class="progress-bar"><div class="progress-fill" style="width:${state.wrong.length?68:0}%"></div></div><strong>${state.wrong.length?68:0}%</strong></div><p class="task-meta" style="margin:12px 0 0">题库包含5道高频辨析题、${chapterQuestions.length}道章节自测和${importedQuestions.length}道资料母题；先看题型，再看解析，最后加入3天复习。</p><p class="question-note">两份“好题精练”为扫描版，已登记到资料索引；当前可直接学习的题目来自两份“100道母题”和章节自测。</p></div><div class="filter-row question-filters"><button class="filter-chip active" data-q-filter="全部">全部</button><button class="filter-chip" data-q-filter="审计">审计</button><button class="filter-chip" data-q-filter="税法">税法</button><button class="filter-chip" data-q-filter="资料母题">资料母题</button><button class="filter-chip" data-q-filter="章节自测">章节自测</button></div><div id="questionList" style="margin-top:14px">${questionBank.map(questionCard).join('')}</div></section>`;document.querySelectorAll('[data-q-filter]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-q-filter]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.qFilter;document.querySelector('#questionList').innerHTML=questionBank.filter(q=>f==='全部'||q.subject===f||q.type===f).map(questionCard).join('');bindPrepared();bindComplete();});}
function renderReview(){app.innerHTML=`<section class="view"><div class="section-head"><div><p class="eyebrow">SPACED REPETITION</p><h2>复习队列</h2></div><span class="tag">3天后复习</span></div><section class="hero" style="min-height:180px;background:#dcecef;color:var(--ink)"><p class="eyebrow" style="color:#2d6675">REVIEW RHYTHM</p><h2 style="font-size:25px;max-width:260px">今天学会，3天后再遇见。</h2><p class="hero-copy" style="color:var(--ink-soft)">完成任务后自动进入复习队列。复习只问三件事：能不能讲、能不能辨、能不能做。</p></section><div class="section-head"><h2>待复习</h2><span class="tag">${state.completed.length?'3':'暂无'} 个到期</span></div><article class="review-card"><div class="review-date"><span>今天 · 复习</span><span>理解 + 回忆</span></div><h3>审计：风险—程序—证据主线</h3><p class="task-meta">尝试不看资料，用三句话解释审计如何形成意见。</p><div class="question-actions" style="margin-top:12px"><button class="primary-button" data-prebuilt="review">开始3分钟复习</button><button class="secondary-button" data-view-jump="library">看知识卡</button></div></article><article class="review-card"><div class="review-date"><span>3天后 · 自动提醒</span><span>错题复盘</span></div><h3>税法：增值税销项税与进项税</h3><p class="task-meta">重新做一道综合题，并记录“错在识别、公式还是计算”。</p></article><p class="insight">复习节奏：当天理解 → 第3天回忆 → 第7天再做题。当前版本先实现3天提醒，后续可继续扩展7天节点。</p></section>`;}
function openModal(title,eyebrow,html){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalEyebrow').textContent=eyebrow;document.querySelector('#modalContent').innerHTML=html;document.querySelector('#modalBackdrop').classList.remove('hidden');}
function bindPrepared(){document.querySelectorAll('[data-explain]').forEach(btn=>btn.onclick=()=>{const k=btn.dataset.explain;if(k==='quick')openModal('章节速记','PREPARED EXPLANATION',`<p>${btn.dataset.text}</p><div class="answer"><strong>学习动作</strong><br>先复述主线，再打开对应章节学习页，最后完成一题。</div>`);if(k==='answer')openModal('题目解析','PREPARED ANSWER',`<p>${btn.dataset.title}</p><div class="answer"><strong>结论</strong><br>${btn.dataset.answer}<br><br><strong>易错原因</strong><br>${btn.dataset.reason}</div>`);if(k==='reason')openModal('错因提示','PREPARED ERROR NOTE',`<p>这道题的主要失分点：<strong>${btn.dataset.reason}</strong></p><div class="answer"><strong>复盘顺序</strong><br>重新读题 → 圈出条件 → 写出规则/公式 → 再算一次。</div>`);});document.querySelectorAll('[data-prebuilt]').forEach(btn=>btn.onclick=()=>{if(btn.dataset.prebuilt==='quiz')openModal('今日重点小测','PREPARED QUIZ',`<p>本组题目已按资料中的高频章节预先整理：</p><ul><li>增值税：征税范围与税率辨析</li><li>企业所得税：纳税调整</li><li>审计：函证控制</li><li>审计：意见类型判断</li><li>土地增值税：扣除项目</li></ul><button class="primary-button" data-go-view="questions">进入题库</button>`);if(btn.dataset.prebuilt==='review')openModal('3分钟复习','PREPARED REVIEW',`<p>请合上资料，完成这条口述：</p><div class="answer">“审计首先识别____，再针对____设计程序，获取____，最后形成____。”</div><p>说完后打开对应章节卡，核对关键词。</p>`);});}
function bindComplete(){document.querySelectorAll('[data-complete]').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.complete);if(state.completed.includes(i))state.completed=state.completed.filter(x=>x!==i);else{state.completed.push(i);state.streak=Math.max(state.streak||0,1);state.studyMinutes=(state.studyMinutes||0)+scheduleTemplates[i][3]*60;}save();document.querySelector('#modalBackdrop').classList.add('hidden');render(currentView);});document.querySelectorAll('[data-wrong]').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.wrong);state.wrong=state.wrong.includes(i)?state.wrong.filter(x=>x!==i):[...state.wrong,i];save();render(currentView);});}
function render(view='home'){currentView=view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));({home:renderHome,plan:renderPlan,library:renderLibrary,questions:renderQuestions,review:renderReview}[view]||renderHome)();bindComplete();bindPrepared();bindStudy();document.querySelectorAll('[data-view-jump]').forEach(x=>x.onclick=()=>render(x.dataset.viewJump));}
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>render(btn.dataset.view));
document.querySelector('#openFocus').onclick=()=>openModal('开始专注学习','FOCUS MODE','<p>选择一个25分钟学习块，完成后记得点击今日任务右侧的圆点。</p><div class="answer"><strong>推荐顺序</strong><br>10分钟理解知识卡 → 10分钟做1道母题 → 5分钟口述/背诵。</div><button class="primary-button" data-close-modal>开始25分钟</button>');
document.querySelector('#closeModal').onclick=()=>document.querySelector('#modalBackdrop').classList.add('hidden');
document.querySelector('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')e.currentTarget.classList.add('hidden');};
document.addEventListener('click',e=>{if(e.target.matches('[data-close-modal]'))document.querySelector('#modalBackdrop').classList.add('hidden');});
document.addEventListener('click',e=>{const view=e.target.closest('[data-go-view]');if(view){document.querySelector('#modalBackdrop').classList.add('hidden');render(view.dataset.goView);}const chapter=e.target.closest('[data-open-chapter]');if(chapter)openChapter(chapter.dataset.openChapter);});
render();
